version: '3'
services:
  influxdb:
    image: influxdb:1.8
    volumes:
      # Mount for influxdb data directory and configuration
      - /influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
volumes:
  influxdb2: